import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle, } from "@/components/ui/card";


const DocumentCard = () => {
	return (
		<div className="flex flex-col overflow-y-auto m-[10%] mt-[4%]">
			<p className="mb-[4%] text-4xl font-bold">Lorem Ipsum</p>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam cursus, metus vel aliquam gravida, metus metus condimentum nibh, ut ullamcorper mi orci sed nulla. Vestibulum risus turpis, cursus at nisl sit amet, porta tincidunt sem. Fusce nec molestie neque, eu tincidunt neque. Maecenas sed sapien faucibus, porttitor purus id, laoreet velit. Ut ut aliquet erat. Etiam egestas nulla at interdum convallis. Praesent pharetra tellus at tellus blandit ultricies. Donec vehicula viverra varius. Donec quam nulla, porttitor nec elit at, finibus vulputate velit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed volutpat, orci id ullamcorper malesuada, quam neque luctus lorem, euismod volutpat sem augue et diam.
				<br/><br/>
				Maecenas elementum metus at vulputate lobortis. Sed rutrum tortor ut risus vestibulum, in ultrices nunc porta. Quisque vehicula porta tristique. Sed eget dolor lobortis, volutpat leo eu, egestas leo. Integer bibendum ipsum sit amet pulvinar imperdiet. Vivamus in viverra quam, id aliquet odio. Praesent mollis elit vitae posuere aliquam. Nam mollis vitae diam eu elementum. Vestibulum pretium eleifend nisl, ac interdum augue scelerisque pharetra. Aenean eget viverra diam. Etiam congue pharetra ultricies. Integer dignissim porttitor laoreet. Morbi non sodales tellus, sed aliquam lacus.
				<br/><br/>
				Quisque at dui in sapien tristique molestie ac sit amet augue. Nunc sed commodo lacus, id iaculis purus. Suspendisse ornare pulvinar augue, id sagittis turpis rhoncus id. Sed eu massa non lorem sodales varius. Morbi fermentum nunc ut risus molestie sagittis. Ut quis magna nec sapien iaculis ullamcorper id egestas magna. Curabitur molestie porttitor diam, quis lobortis nibh eleifend in. Etiam mollis pulvinar fermentum. Sed augue urna, mattis quis magna eget, facilisis ultrices sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed a congue nunc, vel vestibulum leo. Etiam facilisis tristique nibh, vel euismod diam tempor non.
				<br/><br/>
				Maecenas pretium urna eu enim aliquet dignissim. Suspendisse tempor quis eros sed malesuada. Cras commodo vel sem ac tempor. Nunc aliquet diam eu dictum iaculis. Donec lobortis tempus felis, sit amet laoreet nunc tincidunt a. Morbi non risus et erat faucibus ornare. Aenean suscipit quam et sapien malesuada, ac tristique eros dignissim. Aliquam consequat turpis vel consequat congue. In fringilla ex quis massa consectetur, eu commodo augue congue. Suspendisse semper maximus bibendum. Proin dignissim nulla sapien, eu lacinia dui pulvinar nec. Vivamus at imperdiet lacus. Praesent lacinia urna libero. Nulla bibendum lorem nec risus fringilla, sed congue risus scelerisque. Phasellus justo lacus, facilisis eget tellus sit amet, sagittis aliquet ex.
				<br/><br/>
				Etiam tempus auctor enim, in vulputate dui imperdiet quis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam hendrerit, nunc id rutrum interdum, lectus nisl congue massa, a tempor lectus orci sagittis felis. Nulla pulvinar scelerisque facilisis. Sed non tempor ex. Suspendisse quis tellus sit amet augue vehicula consectetur ut id sapien. Maecenas eros sapien, gravida viverra tempor non, accumsan sit amet neque. Pellentesque mattis aliquet finibus. Nullam consequat tellus at euismod vestibulum.
				<br/><br/>
				Ut dictum consequat nunc, in placerat ante sagittis eu. Quisque turpis purus, fringilla eu posuere at, ullamcorper eget ante. Phasellus placerat eros non ante consectetur faucibus. Proin eros eros, ornare in lorem sed, vehicula pharetra justo. Suspendisse scelerisque dignissim nisl vel elementum. Aliquam ornare bibendum lacus vitae scelerisque. Nam tempus nunc sem, ut dictum velit aliquet et. Nam non tempus nulla, non placerat erat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus risus nulla, sodales at bibendum quis, fermentum a lorem. Aenean egestas, tortor non tempus interdum, urna dolor efficitur orci, non lacinia neque sem et magna. In non commodo erat. Donec in venenatis nibh.
				<br/><br/>
				Pellentesque in consequat augue, eu suscipit velit. Donec ultricies commodo augue at commodo. Cras iaculis, nisl eu aliquam iaculis, lectus purus vestibulum neque, et porttitor ipsum risus vitae nisl. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque felis elit, posuere ullamcorper tristique a, maximus in purus. Donec a euismod urna. In libero tortor, tempus non lacus in, finibus efficitur mauris. Maecenas sed ultrices ligula. Praesent consequat id purus ac eleifend. Praesent viverra neque quis justo consectetur, non varius ligula interdum. Proin eget porta elit, quis eleifend ex. Donec at congue velit. In hac habitasse platea dictumst.
				<br/><br/>
				Etiam in velit eget mauris rhoncus suscipit et ac nunc. Nam luctus dictum nisi. Mauris lectus augue, tincidunt vitae dictum at, elementum vitae eros. Proin ac felis pulvinar, consectetur justo eu, pretium diam. Vivamus et risus porta, elementum est a, mollis lectus. Vivamus quis nisi nulla. Etiam pharetra pretium augue sit amet dapibus. Nam orci enim, interdum ac fringilla at, suscipit at mi. Duis ac mi velit. Nam justo ipsum, aliquet vestibulum lectus vel, pharetra commodo lectus. Vivamus sed tempus risus. Vivamus ultrices tellus nec nunc faucibus sollicitudin. Proin lobortis nisi sed arcu ullamcorper, ut pulvinar orci aliquam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
				<br/><br/>
				Suspendisse tincidunt ac ipsum quis egestas. Nulla sit amet nisi consequat, dictum mi ac, cursus velit. Sed ut ultrices justo, posuere dictum nisl. Donec ultrices lectus sit amet commodo sollicitudin. Nunc nec libero at arcu consequat molestie vitae vel magna. Proin sed mi quis ipsum porta venenatis. Pellentesque vitae dui placerat, tincidunt est vel, maximus nisl.
				<br/><br/>
				Fusce dapibus lacus a turpis lobortis varius. Suspendisse tempor augue sit amet dui porta cursus. Praesent in enim id elit finibus vehicula. Vestibulum cursus nibh ut lectus elementum, quis mollis mi faucibus. Sed porta magna est, non mollis tortor gravida ac. In vel mi odio. Curabitur sit amet justo nec urna pharetra efficitur. Quisque consectetur velit vel neque condimentum, vitae semper nisi efficitur. Nam rutrum commodo lorem sit amet blandit. Mauris suscipit rutrum sem, eleifend tincidunt tortor.
			</p>
		</div>
	)
}

export { DocumentCard }
