FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends espeak-ng && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml README.md ./
RUN pip install uv --no-cache-dir  && uv pip install ".[kokoro_cpu]" --no-cache-dir --system --extra-index-url https://download.pytorch.org/whl/cpu

COPY yapit/ /app/yapit

ENV PYTHONUNBUFFERED=1
CMD ["python", "-m", "yapit.workers.kokoro.worker"]
