FROM stackauth/server:53c1c9e

USER root

RUN \
    mkdir -p /var/lib/apt/lists/partial && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean && \
    apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

# Restore base image user
USER node
