"""add soft delete and cross-device sync fields

Revision ID: 01e63e9176ff
Revises: fafa0c537188
Create Date: 2026-01-05 20:18:59.398802

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "01e63e9176ff"
down_revision: Union[str, None] = "fafa0c537188"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userpreferences",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column(
            "pinned_voices",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.add_column("document", sa.Column("last_block_idx", sa.Integer(), nullable=True))
    op.add_column("document", sa.Column("last_played_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("documentprocessor", sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index(op.f("ix_documentprocessor_is_active"), "documentprocessor", ["is_active"], unique=False)
    op.add_column("ttsmodel", sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index(op.f("ix_ttsmodel_is_active"), "ttsmodel", ["is_active"], unique=False)
    op.add_column("voice", sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()))
    op.create_index(op.f("ix_voice_is_active"), "voice", ["is_active"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voice_is_active"), table_name="voice")
    op.drop_column("voice", "is_active")
    op.drop_index(op.f("ix_ttsmodel_is_active"), table_name="ttsmodel")
    op.drop_column("ttsmodel", "is_active")
    op.drop_index(op.f("ix_documentprocessor_is_active"), table_name="documentprocessor")
    op.drop_column("documentprocessor", "is_active")
    op.drop_column("document", "last_played_at")
    op.drop_column("document", "last_block_idx")
    op.drop_table("userpreferences")
    # ### end Alembic commands ###
