"""add document sharing and drop filtered_text

Revision ID: 06b235769fb8
Revises: 8a2a152fad7b
Create Date: 2026-01-12 12:09:37.286590

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06b235769fb8"
down_revision: Union[str, None] = "8a2a152fad7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("is_public", sa.Boolean(), nullable=False))
    op.drop_column("document", "filtered_text")
    op.add_column("userpreferences", sa.Column("auto_import_shared_documents", sa.Boolean(), nullable=False))
    op.add_column("userpreferences", sa.Column("default_documents_public", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userpreferences", "default_documents_public")
    op.drop_column("userpreferences", "auto_import_shared_documents")
    op.add_column("document", sa.Column("filtered_text", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column("document", "is_public")
    # ### end Alembic commands ###
