"""add content_hash to document

Revision ID: 093b1954eca9
Revises: 06b235769fb8
Create Date: 2026-01-12 20:05:58.320425

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "093b1954eca9"
down_revision: Union[str, None] = "06b235769fb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("content_hash", sa.String(), nullable=True))
    op.create_index(op.f("ix_document_content_hash"), "document", ["content_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_content_hash"), table_name="document")
    op.drop_column("document", "content_hash")
    # ### end Alembic commands ###
