"""add highest_tier_subscribed to UserSubscription

Revision ID: 18ecbc440912
Revises: d29aaf752330
Create Date: 2026-01-01 19:37:05.127649

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18ecbc440912"
down_revision: Union[str, None] = "d29aaf752330"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usersubscription",
        sa.Column("highest_tier_subscribed", sa.Enum("free", "basic", "plus", "max", name="plantier"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usersubscription", "highest_tier_subscribed")
    # ### end Alembic commands ###
