"""add ever_paid to user_subscription

Revision ID: 1a82735db431
Revises: 269fc7a6b41b
Create Date: 2026-01-23 19:26:44.951653

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a82735db431"
down_revision: Union[str, None] = "269fc7a6b41b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("usersubscription", sa.Column("ever_paid", sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column("usersubscription", "ever_paid", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usersubscription", "ever_paid")
    # ### end Alembic commands ###
