"""add cancel_at to usersubscription

Revision ID: 269fc7a6b41b
Revises: 29f3df706780
Create Date: 2026-01-23 00:26:45.480568

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "269fc7a6b41b"
down_revision: Union[str, None] = "29f3df706780"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usersubscription", sa.Column("cancel_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usersubscription", "cancel_at")
    # ### end Alembic commands ###
