"""remove block_id from blockvariant

Revision ID: 29f3df706780
Revises: df88ca3f6320
Create Date: 2026-01-19 22:12:51.146791

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29f3df706780"
down_revision: Union[str, None] = "df88ca3f6320"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("blockvariant_block_id_fkey"), "blockvariant", type_="foreignkey")
    op.drop_column("blockvariant", "block_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blockvariant", sa.Column("block_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f("blockvariant_block_id_fkey"), "blockvariant", "block", ["block_id"], ["id"])
    # ### end Alembic commands ###
