"""drop blockvariant cache_ref column

Revision ID: 35603300197f
Revises: ecbda4b1f4a5
Create Date: 2026-02-20 04:59:31.237663

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35603300197f"
down_revision: Union[str, None] = "ecbda4b1f4a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blockvariant", "cache_ref")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blockvariant", sa.Column("cache_ref", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
