"""drop ttsmodel codec columns

Revision ID: 74505cfe9d42
Revises: 387ab1650d59
Create Date: 2026-02-07 14:33:44.932632

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74505cfe9d42"
down_revision: Union[str, None] = "387ab1650d59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ttsmodel", "native_codec")
    op.drop_column("ttsmodel", "channels")
    op.drop_column("ttsmodel", "sample_rate")
    op.drop_column("ttsmodel", "sample_width")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ttsmodel", sa.Column("sample_width", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("ttsmodel", sa.Column("sample_rate", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("ttsmodel", sa.Column("channels", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("ttsmodel", sa.Column("native_codec", sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
