"""add_unique_constraint_usage_period

Revision ID: 7e9cb0dba78a
Revises: a1b2c3d4e5f6
Create Date: 2026-01-24 05:29:52.599591

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e9cb0dba78a"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_usage_period_user_period", "usageperiod", ["user_id", "period_start"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_usage_period_user_period", "usageperiod", type_="unique")
    # ### end Alembic commands ###
