"""add previous_plan_id to usersubscription

Revision ID: 823d6d2ea60a
Revises: 35603300197f
Create Date: 2026-02-24 18:18:21.361154

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "823d6d2ea60a"
down_revision: Union[str, None] = "35603300197f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usersubscription", sa.Column("previous_plan_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usersubscription", "previous_plan_id")
    # ### end Alembic commands ###
