"""drop legacy grace columns

Revision ID: 86c4c0dd6eeb
Revises: cc337b77ee6e
Create Date: 2026-03-31 23:39:29.160386

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "86c4c0dd6eeb"
down_revision: Union[str, None] = "cc337b77ee6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usersubscription", "grace_tier")
    op.drop_column("usersubscription", "grace_until")
    op.drop_column("usersubscription", "previous_plan_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usersubscription", sa.Column("previous_plan_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        "usersubscription",
        sa.Column("grace_until", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    )
    op.add_column(
        "usersubscription",
        sa.Column(
            "grace_tier",
            postgresql.ENUM("free", "basic", "plus", "max", name="plantier"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
