"""add last_rollover_invoice_id to usersubscription

Revision ID: b80d57301967
Revises: c822033c68ff
Create Date: 2026-02-15 20:45:21.100843

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b80d57301967"
down_revision: Union[str, None] = "c822033c68ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usersubscription", sa.Column("last_rollover_invoice_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usersubscription", "last_rollover_invoice_id")
    # ### end Alembic commands ###
