"""add document user_id created index

Revision ID: c822033c68ff
Revises: 74505cfe9d42
Create Date: 2026-02-13 16:33:36.463028

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c822033c68ff"
down_revision: Union[str, None] = "74505cfe9d42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_document_user_created", "document", ["user_id", "created"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_document_user_created", table_name="document")
    # ### end Alembic commands ###
