"""add event_id to usagelog for billing idempotency

Revision ID: cbe49087b51f
Revises: 823d6d2ea60a
Create Date: 2026-02-25 00:14:18.086650

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbe49087b51f"
down_revision: Union[str, None] = "823d6d2ea60a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usagelog", sa.Column("event_id", sa.String(), nullable=True))
    op.create_unique_constraint("usagelog_event_id_key", "usagelog", ["event_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("usagelog_event_id_key", "usagelog", type_="unique")
    op.drop_column("usagelog", "event_id")
    # ### end Alembic commands ###
