"""add extraction_prompt to userpreferences

Revision ID: cc337b77ee6e
Revises: 85cb6dda7bc0
Create Date: 2026-03-31 16:13:53.057917

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc337b77ee6e"
down_revision: Union[str, None] = "85cb6dda7bc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("userpreferences", sa.Column("extraction_prompt", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userpreferences", "extraction_prompt")
    # ### end Alembic commands ###
