"""subscription refactor

Revision ID: d29aaf752330
Revises: efc48e1f9c00
Create Date: 2025-12-31 03:43:36.497503

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d29aaf752330"
down_revision: Union[str, None] = "efc48e1f9c00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tier", sa.Enum("free", "basic", "plus", "max", name="plantier"), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("server_kokoro_characters", sa.Integer(), nullable=True),
        sa.Column("premium_voice_characters", sa.Integer(), nullable=True),
        sa.Column("ocr_pages", sa.Integer(), nullable=True),
        sa.Column("stripe_price_id_monthly", sa.String(), nullable=True),
        sa.Column("stripe_price_id_yearly", sa.String(), nullable=True),
        sa.Column("trial_days", sa.Integer(), nullable=False),
        sa.Column("price_cents_monthly", sa.Integer(), nullable=False),
        sa.Column("price_cents_yearly", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plan_tier"), "plan", ["tier"], unique=True)
    op.create_table(
        "usagelog",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("type", sa.Enum("server_kokoro", "premium_voice", "ocr", name="usagetype"), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reference_id", sa.String(), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_usage_log_created", "usagelog", ["created"], unique=False)
    op.create_index("idx_usage_log_user_created", "usagelog", ["user_id", "created"], unique=False)
    op.create_index(op.f("ix_usagelog_reference_id"), "usagelog", ["reference_id"], unique=False)
    op.create_index(op.f("ix_usagelog_user_id"), "usagelog", ["user_id"], unique=False)
    op.create_table(
        "usageperiod",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("server_kokoro_characters", sa.Integer(), nullable=False),
        sa.Column("premium_voice_characters", sa.Integer(), nullable=False),
        sa.Column("ocr_pages", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_usage_period_user_period", "usageperiod", ["user_id", "period_start"], unique=False)
    op.create_index(op.f("ix_usageperiod_user_id"), "usageperiod", ["user_id"], unique=False)
    op.create_table(
        "usersubscription",
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "trialing", "past_due", "canceled", "incomplete", name="subscriptionstatus"),
            nullable=False,
        ),
        sa.Column("stripe_customer_id", sa.String(), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plan.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_usersubscription_stripe_customer_id"), "usersubscription", ["stripe_customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_usersubscription_stripe_subscription_id"), "usersubscription", ["stripe_subscription_id"], unique=True
    )
    op.drop_column("documentprocessor", "credits_per_page")
    op.drop_column("ttsmodel", "credits_per_sec")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ttsmodel", sa.Column("credits_per_sec", sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False)
    )
    op.add_column(
        "documentprocessor",
        sa.Column("credits_per_page", sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_usersubscription_stripe_subscription_id"), table_name="usersubscription")
    op.drop_index(op.f("ix_usersubscription_stripe_customer_id"), table_name="usersubscription")
    op.drop_table("usersubscription")
    op.drop_index(op.f("ix_usageperiod_user_id"), table_name="usageperiod")
    op.drop_index("idx_usage_period_user_period", table_name="usageperiod")
    op.drop_table("usageperiod")
    op.drop_index(op.f("ix_usagelog_user_id"), table_name="usagelog")
    op.drop_index(op.f("ix_usagelog_reference_id"), table_name="usagelog")
    op.drop_index("idx_usage_log_user_created", table_name="usagelog")
    op.drop_index("idx_usage_log_created", table_name="usagelog")
    op.drop_table("usagelog")
    op.drop_index(op.f("ix_plan_tier"), table_name="plan")
    op.drop_table("plan")
    # ### end Alembic commands ###
