"""token billing model changes

Revision ID: df88ca3f6320
Revises: 093b1954eca9
Create Date: 2026-01-19 17:46:30.566285

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "df88ca3f6320"
down_revision: Union[str, None] = "093b1954eca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Plan: add ocr_tokens, drop ocr_pages
    op.add_column("plan", sa.Column("ocr_tokens", sa.Integer(), nullable=True))
    op.drop_column("plan", "ocr_pages")

    # UsagePeriod: add ocr_tokens (default 0 for existing rows), drop ocr_pages
    op.add_column("usageperiod", sa.Column("ocr_tokens", sa.Integer(), nullable=False, server_default="0"))
    op.alter_column("usageperiod", "ocr_tokens", server_default=None)
    op.drop_column("usageperiod", "ocr_pages")

    # UserSubscription: add rollover/purchased fields (default 0 for existing rows)
    op.add_column("usersubscription", sa.Column("rollover_tokens", sa.Integer(), nullable=False, server_default="0"))
    op.add_column(
        "usersubscription", sa.Column("rollover_voice_chars", sa.Integer(), nullable=False, server_default="0")
    )
    op.add_column("usersubscription", sa.Column("purchased_tokens", sa.Integer(), nullable=False, server_default="0"))
    op.add_column(
        "usersubscription", sa.Column("purchased_voice_chars", sa.Integer(), nullable=False, server_default="0")
    )
    # Remove server defaults after applying to existing rows
    op.alter_column("usersubscription", "rollover_tokens", server_default=None)
    op.alter_column("usersubscription", "rollover_voice_chars", server_default=None)
    op.alter_column("usersubscription", "purchased_tokens", server_default=None)
    op.alter_column("usersubscription", "purchased_voice_chars", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usersubscription", "purchased_voice_chars")
    op.drop_column("usersubscription", "purchased_tokens")
    op.drop_column("usersubscription", "rollover_voice_chars")
    op.drop_column("usersubscription", "rollover_tokens")
    op.add_column("usageperiod", sa.Column("ocr_pages", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column("usageperiod", "ocr_tokens")
    op.add_column("plan", sa.Column("ocr_pages", sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column("plan", "ocr_tokens")
    # ### end Alembic commands ###
