"""add user_voice_stats table

Revision ID: ecbda4b1f4a5
Revises: b80d57301967
Create Date: 2026-02-18 22:35:31.912774

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecbda4b1f4a5"
down_revision: Union[str, None] = "b80d57301967"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uservoicestats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("voice_slug", sa.String(), nullable=False),
        sa.Column("model_slug", sa.String(), nullable=False),
        sa.Column("month", sa.Date(), nullable=False),
        sa.Column("total_characters", sa.Integer(), nullable=False),
        sa.Column("total_duration_ms", sa.Integer(), nullable=False),
        sa.Column("synth_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "voice_slug", "model_slug", "month", name="uq_user_voice_stats"),
    )
    op.create_index(op.f("ix_uservoicestats_user_id"), "uservoicestats", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_uservoicestats_user_id"), table_name="uservoicestats")
    op.drop_table("uservoicestats")
    # ### end Alembic commands ###
