"""initial schema

Revision ID: efc48e1f9c00
Revises:
Create Date: 2025-12-25 17:44:00.079378

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "efc48e1f9c00"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creditpackage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_price_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("credits", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_creditpackage_provider_price_id"), "creditpackage", ["provider_price_id"], unique=True)
    op.create_table(
        "document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("original_text", sa.TEXT(), nullable=True),
        sa.Column("filtered_text", sa.TEXT(), nullable=True),
        sa.Column(
            "last_applied_filter_config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("extraction_method", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("structured_content", sa.TEXT(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "metadata", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documentprocessor",
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("credits_per_page", sa.DECIMAL(precision=10, scale=4), nullable=False),
        sa.PrimaryKeyConstraint("slug"),
    )
    op.create_table(
        "filter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "config", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=True
        ),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_filter_name"), "filter", ["name"], unique=False)
    op.create_index(op.f("ix_filter_user_id"), "filter", ["user_id"], unique=False)
    op.create_table(
        "ttsmodel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("credits_per_sec", sa.DECIMAL(precision=10, scale=4), nullable=False),
        sa.Column("sample_rate", sa.Integer(), nullable=False),
        sa.Column("channels", sa.Integer(), nullable=False),
        sa.Column("sample_width", sa.Integer(), nullable=False),
        sa.Column("native_codec", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ttsmodel_slug"), "ttsmodel", ["slug"], unique=True)
    op.create_table(
        "usercredits",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("balance", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("total_purchased", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("total_used", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "block",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("text", sa.TEXT(), nullable=True),
        sa.Column("est_duration_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "credittransaction",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "credit_purchase",
                "credit_bonus",
                "credit_refund",
                "credit_adjustment",
                "usage_deduction",
                name="transactiontype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status", sa.Enum("pending", "completed", "failed", "reversed", name="transactionstatus"), nullable=False
        ),
        sa.Column("amount", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("balance_before", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("balance_after", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("external_reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("usage_reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["usercredits.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_credit_transaction_created", "credittransaction", ["created"], unique=False)
    op.create_index("idx_credit_transaction_user_created", "credittransaction", ["user_id", "created"], unique=False)
    op.create_index(
        op.f("ix_credittransaction_external_reference"), "credittransaction", ["external_reference"], unique=False
    )
    op.create_index(
        op.f("ix_credittransaction_usage_reference"), "credittransaction", ["usage_reference"], unique=False
    )
    op.create_index(op.f("ix_credittransaction_user_id"), "credittransaction", ["user_id"], unique=False)
    op.create_table(
        "userusagestats",
        sa.Column("user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("total_seconds_synthesized", sa.DECIMAL(precision=19, scale=4), nullable=False),
        sa.Column("total_characters_processed", sa.Integer(), nullable=False),
        sa.Column("total_requests", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["usercredits.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "voice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lang", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "parameters", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["ttsmodel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", "model_id", name="unique_voice_per_model"),
    )
    op.create_table(
        "blockvariant",
        sa.Column("hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("block_id", sa.Integer(), nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("voice_id", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("cache_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["block_id"],
            ["block.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["ttsmodel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voice_id"],
            ["voice.id"],
        ),
        sa.PrimaryKeyConstraint("hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blockvariant")
    op.drop_table("voice")
    op.drop_table("userusagestats")
    op.drop_index(op.f("ix_credittransaction_user_id"), table_name="credittransaction")
    op.drop_index(op.f("ix_credittransaction_usage_reference"), table_name="credittransaction")
    op.drop_index(op.f("ix_credittransaction_external_reference"), table_name="credittransaction")
    op.drop_index("idx_credit_transaction_user_created", table_name="credittransaction")
    op.drop_index("idx_credit_transaction_created", table_name="credittransaction")
    op.drop_table("credittransaction")
    op.drop_table("block")
    op.drop_table("usercredits")
    op.drop_index(op.f("ix_ttsmodel_slug"), table_name="ttsmodel")
    op.drop_table("ttsmodel")
    op.drop_index(op.f("ix_filter_user_id"), table_name="filter")
    op.drop_index(op.f("ix_filter_name"), table_name="filter")
    op.drop_table("filter")
    op.drop_table("documentprocessor")
    op.drop_table("document")
    op.drop_index(op.f("ix_creditpackage_provider_price_id"), table_name="creditpackage")
    op.drop_table("creditpackage")
    # ### end Alembic commands ###
