"""add usage_multiplier to ttsmodel

Revision ID: fafa0c537188
Revises: 1bfa956c76b4
Create Date: 2026-01-03 01:50:19.905062

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fafa0c537188"
down_revision: Union[str, None] = "1bfa956c76b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ttsmodel", sa.Column("usage_multiplier", sa.Float(), nullable=False, server_default="1.0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ttsmodel", "usage_multiplier")
    # ### end Alembic commands ###
